spring: 
  profiles: 
    active:
    - dev
---
spring:
  profiles: dev #开发
  application: 
    name: microservicecloud-config-w4xj-dev
---
spring:
  profiles: test #测试环境
  application: 
    name: microservicecloud-config-w4xj-test  
#请保存为UTF-8